# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b0c6a4cc8f9f88943d0f757f9a3d02e8ceaffde8cf18193dd41b3f8f1a359c25c813633d2625e329f927219462ad0b6e0073f3c1a82d32c5ea3cc932abcaef

test:
  secret_key_base: 54116c3bcb1cd89d145113865409754722d26091597d4e0b48c34f4880263b88a04117c096bcec1bb7707240be5386cc81e436b9c7945c245ee4827cc7d2f252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
